<?php
class cars{
     protected  $carname;
     protected $carss=[];

    /**
     * cars constructor.
     * @param array $carss
     */
    public function __construct($carname,$carss=[])
    {

        $this->carname=$carname;
        $this->carss=$carss;
    }

    /**
     * @return mixed
     */
    public function Carname()
    {
        return $this->carname;
    }

    public function carrs(){
        return $this->carss;
    }
    public function addcar($carname){
        $this->carss[]=$carname;
    }



    public function  say(){
        echo "we are all cars n we dont give a fuck";

         }
}

/*class sportscar{
    public function doing(){

        echo "we move at a supersonic speed";

    }
  public function say()
  {
      parent::say(); // TODO: Change the autogenerated stub
  }

}*/

$benz=new cars('benz',[
    'kim',
    'kimani',
    'ianoh',
    'raf'
]);




var_dump($benz->carrs());

?>